//
//  DataManager.swift
//  FontViewer
//
//  Created by tunko on 2019/10/22.
//  Copyright © 2019 tunko. All rights reserved.
//

import UIKit

class DataManager
{
    static let shared = DataManager()
    
    var commitCheck = false
    
    var dataFontList : [String] = [
        "NanumSquareOTF",
        "NanumSquareOTFB",
        "NanumSquareOTFR",
        "NanumSquareOTFEB",
        "NanumSquareOTFL",
        "Noto Nastaliq Urdu",
        "NotoNastaliqUrdu",
        "NotoNastaliqUrdu-Bold",
        "Noto Sans Oriya",
        "NotoSansOriya-Bold",
        "NotoSansOriya",
        "Noto Sans Kannada",
        "NotoSansKannada-Bold",
        "NotoSansKannada-Light",
        "NotoSansKannada-Regular",
        "--여기부터 기본 폰트-- (맥기준)",
        "Copperplate",
        "Copperplate-Light",
        "Copperplate",
        "Copperplate-Bold",
        "Apple SD Gothic Neo",
        "AppleSDGothicNeo-Thin",
        "AppleSDGothicNeo-Light",
        "AppleSDGothicNeo-Regular",
        "AppleSDGothicNeo-Bold",
        "AppleSDGothicNeo-SemiBold",
        "AppleSDGothicNeo-UltraLight",
        "AppleSDGothicNeo-Medium",
        "Thonburi",
        "Thonburi",
        "Thonburi-Light",
        "Thonburi-Bold",
        "Gill Sans",
        "GillSans-Italic",
        "GillSans-SemiBold",
        "GillSans-UltraBold",
        "GillSans-Light",
        "GillSans-Bold",
        "GillSans",
        "GillSans-SemiBoldItalic",
        "GillSans-BoldItalic",
        "GillSans-LightItalic",
        "Marker Felt",
        "MarkerFelt-Thin",
        "MarkerFelt-Wide",
        "Hiragino Maru Gothic ProN",
        "HiraMaruProN-W4",
        "Courier New",
        "CourierNewPS-ItalicMT",
        "CourierNewPSMT",
        "CourierNewPS-BoldItalicMT",
        "CourierNewPS-BoldMT",
        "Kohinoor Telugu",
        "KohinoorTelugu-Regular",
        "KohinoorTelugu-Medium",
        "KohinoorTelugu-Light",
        "Avenir Next Condensed",
        "AvenirNextCondensed-Heavy",
        "AvenirNextCondensed-MediumItalic",
        "AvenirNextCondensed-Regular",
        "AvenirNextCondensed-UltraLightItalic",
        "AvenirNextCondensed-Medium",
        "AvenirNextCondensed-HeavyItalic",
        "AvenirNextCondensed-DemiBoldItalic",
        "AvenirNextCondensed-Bold",
        "AvenirNextCondensed-DemiBold",
        "AvenirNextCondensed-BoldItalic",
        "AvenirNextCondensed-Italic",
        "AvenirNextCondensed-UltraLight",
        "Tamil Sangam MN",
        "TamilSangamMN",
        "TamilSangamMN-Bold",
        "Helvetica Neue",
        "HelveticaNeue-UltraLightItalic",
        "HelveticaNeue-Medium",
        "HelveticaNeue-MediumItalic",
        "HelveticaNeue-UltraLight",
        "HelveticaNeue-Italic",
        "HelveticaNeue-Light",
        "HelveticaNeue-ThinItalic",
        "HelveticaNeue-LightItalic",
        "HelveticaNeue-Bold",
        "HelveticaNeue-Thin",
        "HelveticaNeue-CondensedBlack",
        "HelveticaNeue",
        "HelveticaNeue-CondensedBold",
        "HelveticaNeue-BoldItalic",
        "Times New Roman",
        "TimesNewRomanPS-ItalicMT",
        "TimesNewRomanPS-BoldItalicMT",
        "TimesNewRomanPS-BoldMT",
        "TimesNewRomanPSMT",
        "Georgia",
        "Georgia-BoldItalic",
        "Georgia-Italic",
        "Georgia",
        "Georgia-Bold",
        "Sinhala Sangam MN",
        "SinhalaSangamMN-Bold",
        "SinhalaSangamMN",
        "Arial Rounded MT Bold",
        "ArialRoundedMTBold",
        "Kailasa",
        "Kailasa-Bold",
        "Kailasa",
        "Kohinoor Devanagari",
        "KohinoorDevanagari-Regular",
        "KohinoorDevanagari-Light",
        "KohinoorDevanagari-Semibold",
        "Kohinoor Bangla",
        "KohinoorBangla-Regular",
        "KohinoorBangla-Semibold",
        "KohinoorBangla-Light",
        "Chalkboard SE",
        "ChalkboardSE-Bold",
        "ChalkboardSE-Light",
        "ChalkboardSE-Regular",
        "Apple Color Emoji",
        "AppleColorEmoji",
        "PingFang TC",
        "PingFangTC-Regular",
        "PingFangTC-Thin",
        "PingFangTC-Medium",
        "PingFangTC-Semibold",
        "PingFangTC-Light",
        "PingFangTC-Ultralight",
        "Geeza Pro",
        "GeezaPro-Bold",
        "GeezaPro",
        "Damascus",
        "DamascusBold",
        "DamascusLight",
        "Damascus",
        "DamascusMedium",
        "DamascusSemiBold",
        "Noteworthy",
        "Noteworthy-Bold",
        "Noteworthy-Light",
        "Avenir",
        "Avenir-Oblique",
        "Avenir-HeavyOblique",
        "Avenir-Heavy",
        "Avenir-BlackOblique",
        "Avenir-BookOblique",
        "Avenir-Roman",
        "Avenir-Medium",
        "Avenir-Black",
        "Avenir-Light",
        "Avenir-MediumOblique",
        "Avenir-Book",
        "Avenir-LightOblique",
        "Kohinoor Gujarati",
        "KohinoorGujarati-Light",
        "KohinoorGujarati-Bold",
        "KohinoorGujarati-Regular",
        "Mishafi",
        "DiwanMishafi",
        "Academy Engraved LET",
        "AcademyEngravedLetPlain",
        "Party LET",
        "PartyLetPlain",
        "Futura",
        "Futura-CondensedExtraBold",
        "Futura-Medium",
        "Futura-Bold",
        "Futura-CondensedMedium",
        "Futura-MediumItalic",
        "Arial Hebrew",
        "ArialHebrew-Bold",
        "ArialHebrew-Light",
        "ArialHebrew",
        "Farah",
        "Farah",
        "Mukta Mahee",
        "MuktaMahee-Light",
        "MuktaMahee-Bold",
        "MuktaMahee-Regular",
        "Noto Sans Myanmar",
        "NotoSansMyanmar-Regular",
        "NotoSansMyanmar-Bold",
        "NotoSansMyanmar-Light",
        "Arial",
        "Arial-BoldMT",
        "Arial-BoldItalicMT",
        "Arial-ItalicMT",
        "ArialMT",
        "Chalkduster",
        "Chalkduster",
        "Kefa",
        "Kefa-Regular",
        "Hoefler Text",
        "HoeflerText-Italic",
        "HoeflerText-Black",
        "HoeflerText-Regular",
        "HoeflerText-BlackItalic",
        "Optima",
        "Optima-ExtraBlack",
        "Optima-BoldItalic",
        "Optima-Italic",
        "Optima-Regular",
        "Optima-Bold",
        "Galvji",
        "Galvji-Bold",
        "Galvji",
        "Palatino",
        "Palatino-Italic",
        "Palatino-Roman",
        "Palatino-BoldItalic",
        "Palatino-Bold",
        "Malayalam Sangam MN",
        "MalayalamSangamMN-Bold",
        "MalayalamSangamMN",
        "Al Nile",
        "AlNile",
        "AlNile-Bold",
        "Lao Sangam MN",
        "LaoSangamMN",
        "Bradley Hand",
        "BradleyHandITCTT-Bold",
        "Hiragino Mincho ProN",
        "HiraMinProN-W3",
        "HiraMinProN-W6",
        "PingFang HK",
        "PingFangHK-Medium",
        "PingFangHK-Thin",
        "PingFangHK-Regular",
        "PingFangHK-Ultralight",
        "PingFangHK-Semibold",
        "PingFangHK-Light",
        "Helvetica",
        "Helvetica-Oblique",
        "Helvetica-BoldOblique",
        "Helvetica",
        "Helvetica-Light",
        "Helvetica-Bold",
        "Helvetica-LightOblique",
        "Courier",
        "Courier-BoldOblique",
        "Courier-Oblique",
        "Courier",
        "Courier-Bold",
        "Cochin",
        "Cochin-Italic",
        "Cochin-Bold",
        "Cochin",
        "Cochin-BoldItalic",
        "Trebuchet MS",
        "TrebuchetMS-Bold",
        "TrebuchetMS-Italic",
        "Trebuchet-BoldItalic",
        "TrebuchetMS",
        "Devanagari Sangam MN",
        "DevanagariSangamMN",
        "DevanagariSangamMN-Bold",
        "Rockwell",
        "Rockwell-Italic",
        "Rockwell-Regular",
        "Rockwell-Bold",
        "Rockwell-BoldItalic",
        "Snell Roundhand",
        "SnellRoundhand",
        "SnellRoundhand-Bold",
        "SnellRoundhand-Black",
        "Zapf Dingbats",
        "ZapfDingbatsITC",
        "Bodoni 72",
        "BodoniSvtyTwoITCTT-Bold",
        "BodoniSvtyTwoITCTT-BookIta",
        "BodoniSvtyTwoITCTT-Book",
        "Verdana",
        "Verdana-Italic",
        "Verdana",
        "Verdana-Bold",
        "Verdana-BoldItalic",
        "American Typewriter",
        "AmericanTypewriter-CondensedBold",
        "AmericanTypewriter-Condensed",
        "AmericanTypewriter-CondensedLight",
        "AmericanTypewriter",
        "AmericanTypewriter-Bold",
        "AmericanTypewriter-Semibold",
        "AmericanTypewriter-Light",
        "Avenir Next",
        "AvenirNext-Medium",
        "AvenirNext-DemiBoldItalic",
        "AvenirNext-DemiBold",
        "AvenirNext-HeavyItalic",
        "AvenirNext-Regular",
        "AvenirNext-Italic",
        "AvenirNext-MediumItalic",
        "AvenirNext-UltraLightItalic",
        "AvenirNext-BoldItalic",
        "AvenirNext-Heavy",
        "AvenirNext-Bold",
        "AvenirNext-UltraLight",
        "Baskerville",
        "Baskerville-SemiBoldItalic",
        "Baskerville-SemiBold",
        "Baskerville-BoldItalic",
        "Baskerville",
        "Baskerville-Bold",
        "Baskerville-Italic",
        "Khmer Sangam MN",
        "KhmerSangamMN",
        "Didot",
        "Didot-Bold",
        "Didot",
        "Didot-Italic",
        "Savoye LET",
        "SavoyeLetPlain",
        "Bodoni Ornaments",
        "BodoniOrnamentsITCTT",
        "Symbol",
        "Symbol",
        "Charter",
        "Charter-BlackItalic",
        "Charter-Bold",
        "Charter-Roman",
        "Charter-Black",
        "Charter-BoldItalic",
        "Charter-Italic",
        "Menlo",
        "Menlo-BoldItalic",
        "Menlo-Bold",
        "Menlo-Italic",
        "Menlo-Regular",
        "Bodoni 72 Smallcaps",
        "BodoniSvtyTwoSCITCTT-Book",
        "DIN Alternate",
        "DINAlternate-Bold",
        "Papyrus",
        "Papyrus-Condensed",
        "Papyrus",
        "Hiragino Sans",
        "HiraginoSans-W3",
        "HiraginoSans-W6",
        "HiraginoSans-W7",
        "PingFang SC",
        "PingFangSC-Medium",
        "PingFangSC-Semibold",
        "PingFangSC-Light",
        "PingFangSC-Ultralight",
        "PingFangSC-Regular",
        "PingFangSC-Thin",
        "Myanmar Sangam MN",
        "MyanmarSangamMN",
        "MyanmarSangamMN-Bold",
        "Apple Symbols",
        "AppleSymbols",
        "Zapfino",
        "Zapfino",
        "Bodoni 72 Oldstyle",
        "BodoniSvtyTwoOSITCTT-BookIt",
        "BodoniSvtyTwoOSITCTT-Book",
        "BodoniSvtyTwoOSITCTT-Bold",
        "Euphemia UCAS",
        "EuphemiaUCAS",
        "EuphemiaUCAS-Italic",
        "EuphemiaUCAS-Bold",
        "DIN Condensed",
        "DINCondensed-Bold"
    ]
}
